In [1]:
from astropy.io import fits
from astropy.table import Table
import numpy as np
import matplotlib.pylab as plt 
import matplotlib.lines as mlines
from matplotlib.legend import Legend
from pythonds.basic.stack import Stack
from math import *
from sklearn.neighbors import KDTree
from lrg_plot_functions import *
from lrg_sum_functions import *
from cosmo_Calc import *
from divideByTwo import *
from read_data import *
from nearNeighbors import *
from scipy import stats
from astropy import stats
import healpy as hp
from localBKG_and_interlopersHEALPix import *
# import healpy as hpy
from makeCutoutTableFunc import *
from plotHistogramProjections3D import *
from read_bricks import *
from mpl_toolkits.axes_grid1 import make_axes_locatable
import random

In [2]:
# read in LRG data

data_raLRG = np.load('/Users/mtownsend/Documents/LRG_Data/ra_LRG.npz')
raLRG = data_raLRG['ra_LRG']

data_decLRG = np.load('/Users/mtownsend/Documents/LRG_Data/dec_LRG.npz')
decLRG = data_decLRG['dec_LRG']

data_zLRG = np.load('/Users/mtownsend/Documents/LRG_Data/z_LRG.npz')
zLRG = data_zLRG['z_LRG']

data_gmagLRG = np.load('/Users/mtownsend/Documents/LRG_Data/gmag_LRG.npz')
gmagLRG = data_gmagLRG['gmag_LRG']

data_rmagLRG = np.load('/Users/mtownsend/Documents/LRG_Data/rmag_LRG.npz')
rmagLRG = data_rmagLRG['rmag_LRG']

data_zmagLRG = np.load('/Users/mtownsend/Documents/LRG_Data/zmag_LRG.npz')
zmagLRG = data_zmagLRG['zmag_LRG']

data_grcolorLRG = np.load('/Users/mtownsend/Documents/LRG_Data/grcolor_LRG.npz')
grcolorLRG = data_grcolorLRG['grcolor_LRG']

data_rzcolorLRG = np.load('/Users/mtownsend/Documents/LRG_Data/rzcolor_LRG.npz')
rzcolorLRG = data_rzcolorLRG['rzcolor_LRG']


# read in BKG data

data_raBKG = np.load('/Users/mtownsend/Documents/LRG_Data/ra_BKG.npz')
raBKG = data_raBKG['ra_BKG']

data_decBKG = np.load('/Users/mtownsend/Documents/LRG_Data/dec_BKG.npz')
decBKG = data_decBKG['dec_BKG']

data_gmagBKG = np.load('/Users/mtownsend/Documents/LRG_Data/gmag_BKG.npz')
gmagBKG = data_gmagBKG['gmag_BKG']

data_rmagBKG = np.load('/Users/mtownsend/Documents/LRG_Data/rmag_BKG.npz')
rmagBKG = data_rmagBKG['rmag_BKG']

data_zmagBKG = np.load('/Users/mtownsend/Documents/LRG_Data/zmag_BKG.npz')
zmagBKG = data_zmagBKG['zmag_BKG']

data_grcolorBKG = np.load('/Users/mtownsend/Documents/LRG_Data/grcolor_BKG.npz')
grcolorBKG = data_grcolorBKG['grcolor_BKG']

data_rzcolorBKG = np.load('/Users/mtownsend/Documents/LRG_Data/rzcolor_BKG.npz')
rzcolorBKG = data_rzcolorBKG['rzcolor_BKG']


# read in combined LRG and BKG data

data_ra = np.load('/Users/mtownsend/Documents/LRG_Data/ra_total.npz')
ra_total = data_ra['ra']

data_dec = np.load('/Users/mtownsend/Documents/LRG_Data/dec_total.npz')
dec_total = data_dec['dec']

data_gmag = np.load('/Users/mtownsend/Documents/LRG_Data/gmag_total.npz')
gmag_total = data_gmag['gmag']

data_rmag = np.load('/Users/mtownsend/Documents/LRG_Data/rmag_total.npz')
rmag_total = data_rmag['rmag']

data_zmag = np.load('/Users/mtownsend/Documents/LRG_Data/zmag_total.npz')
zmag_total = data_zmag['zmag']

data_grcolor = np.load('/Users/mtownsend/Documents/LRG_Data/grcolor_total.npz')
grcolor_total = data_grcolor['grcolor']

data_rzcolor = np.load('/Users/mtownsend/Documents/LRG_Data/rzcolor_total.npz')
rzcolor_total = data_rzcolor['rzcolor']




In [3]:
# read in null results (lowz)

data_Nsat25_low = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat25_low.npz')
low_null_25 = data_Nsat25_low['Nsat25']


data_Nsat03_low = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat03_low.npz')
low_null_Nsat_03 = data_Nsat03_low['Nsat03']



In [4]:
# read in null results (mid1)

data_Nsat25_mid1 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat25_mid1.npz')
mid1_null_25 = data_Nsat25_mid1['Nsat25']

data_Nsat03_mid1 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat03_mid1.npz')
mid1_null_Nsat_03 = data_Nsat03_mid1['Nsat03']

data_Nsat35_mid1 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat35_mid1.npz')
mid1_null_Nsat_35 = data_Nsat35_mid1['Nsat35']

data_Nsat04_mid1 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat04_mid1.npz')
mid1_null_Nsat_04 = data_Nsat04_mid1['Nsat04']


In [5]:
# read in null results (mid2)

data_Nsat25_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat25_mid2.npz')
mid2_null_25 = data_Nsat25_mid2['Nsat25']

data_Nsat03_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat03_mid2.npz')
mid2_null_Nsat_03 = data_Nsat03_mid2['Nsat03']

data_Nsat35_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat35_mid2.npz')
mid2_null_Nsat_35 = data_Nsat35_mid2['Nsat35']

data_Nsat04_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat04_mid2.npz')
mid2_null_Nsat_04 = data_Nsat04_mid2['Nsat04']

data_Nsat45_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat45_mid2.npz')
mid2_null_Nsat_45 = data_Nsat45_mid2['Nsat45']

data_Nsat05_mid2 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat05_mid2.npz')
mid2_null_Nsat_05 = data_Nsat05_mid2['Nsat05']


In [6]:
# read in null results (mid3)

data_Nsat25_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat25_mid3.npz')
mid3_null_25 = data_Nsat25_mid3['Nsat25']

data_Nsat03_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat03_mid3.npz')
mid3_null_Nsat_03 = data_Nsat03_mid3['Nsat03']

data_Nsat35_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat35_mid3.npz')
mid3_null_Nsat_35 = data_Nsat35_mid3['Nsat35']

data_Nsat04_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat04_mid3.npz')
mid3_null_Nsat_04 = data_Nsat04_mid3['Nsat04']

data_Nsat45_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat45_mid3.npz')
mid3_null_Nsat_45 = data_Nsat45_mid3['Nsat45']

data_Nsat05_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat05_mid3.npz')
mid3_null_Nsat_05 = data_Nsat05_mid3['Nsat05']

data_Nsat55_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat55_mid3.npz')
mid3_null_Nsat_55 = data_Nsat55_mid3['Nsat55']

data_Nsat06_mid3 = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat06_mid3.npz')
mid3_null_Nsat_06 = data_Nsat06_mid3['Nsat06']


In [7]:
# read in null results (highz)

data_Nsat25_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat25_high.npz')
high_null_25 = data_Nsat25_high['Nsat25']

data_Nsat03_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat03_high.npz')
high_null_Nsat_03 = data_Nsat03_high['Nsat03']

data_Nsat35_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat35_high.npz')
high_null_Nsat_35 = data_Nsat35_high['Nsat35']

data_Nsat04_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat04_high.npz')
high_null_Nsat_04 = data_Nsat04_high['Nsat04']

data_Nsat45_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat45_high.npz')
high_null_Nsat_45 = data_Nsat45_high['Nsat45']

data_Nsat05_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat05_high.npz')
high_null_Nsat_05 = data_Nsat05_high['Nsat05']

data_Nsat55_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat55_high.npz')
high_null_Nsat_55 = data_Nsat55_high['Nsat55']

data_Nsat06_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat06_high.npz')
high_null_Nsat_06 = data_Nsat06_high['Nsat06']

data_Nsat65_high = np.load('/Users/mtownsend/Documents/LRG_Data/null_Nsat65_high.npz')
high_null_Nsat_65 = data_Nsat65_high['Nsat65']

In [8]:
# read in selection matrices for each luminosity selected sample 

data_smatrix03 = np.load('/Users/mtownsend/Desktop/lowz_smatrix-2matrices.npz')
smatrix03 = data_smatrix03['smatrix_low']
print(smatrix03.shape)

data_smatrix04 = np.load('/Users/mtownsend/Desktop/midz1_smatrix-4matrices.npz')
smatrix04 = data_smatrix04['smatrix_low']
print(smatrix04.shape)

data_smatrix05 = np.load('/Users/mtownsend/Desktop/midz2_smatrix-6matrices.npz')
smatrix05 = data_smatrix05['smatrix_low']
print(smatrix05.shape)

data_smatrix06 = np.load('/Users/mtownsend/Desktop/midz3_smatrix-8matrices.npz')
smatrix06 = data_smatrix06['smatrix_low']
print(smatrix06.shape)

data_smatrix65 = np.load('/Users/mtownsend/Desktop/highz_smatrix-9matrices.npz')
smatrix65 = data_smatrix65['smatrix_low']
print(smatrix65.shape)


(2, 49, 49, 49)
(4, 49, 49, 49)
(6, 49, 49, 49)
(8, 49, 49, 49)
(9, 49, 49, 49)


In [9]:
# color-color-magnitude bins

rz_edges = np.array([-1.8027077, -1.5527076721191406, -1.3027076721191406, -1.0527076721191406, -0.8027076721191406, -0.5527076721191406, -0.3027076721191406, -0.052707672119140625, 0.19729232788085938, 0.4472923278808594, 0.6972923278808594, 0.9472923278808594, 1.1972923278808594, 1.4472923278808594, 1.6972923278808594, 1.9472923278808594, 2.1972923278808594, 2.4472923278808594, 2.6972923278808594, 2.9472923278808594, 3.1972923278808594, 3.4472923278808594, 3.6972923278808594, 3.9472923278808594, 4.197292327880859, 4.447292327880859, 4.697292327880859, 4.947292327880859, 5.197292327880859, 5.447292327880859, 5.697292327880859, 5.947292327880859, 6.197292327880859, 6.447292327880859, 6.697292327880859, 6.947292327880859, 7.197292327880859, 7.447292327880859, 7.697292327880859, 7.947292327880859, 8.19729232788086, 8.44729232788086, 8.69729232788086, 8.94729232788086, 9.19729232788086, 9.44729232788086, 9.69729232788086, 9.94729232788086, 10.19729232788086, 10.44729232788086])
gr_edges = np.array([-6.5846786, -6.234678649902344, -5.8846786499023445, -5.534678649902345, -5.184678649902345, -4.8346786499023455, -4.484678649902346, -4.134678649902346, -3.784678649902346, -3.434678649902346, -3.084678649902346, -2.734678649902346, -2.384678649902346, -2.0346786499023457, -1.6846786499023456, -1.3346786499023455, -0.9846786499023455, -0.6346786499023456, -0.2846786499023456, 0.06532135009765438, 0.41532135009765436, 0.7653213500976543, 1.1153213500976542, 1.4653213500976543, 1.8153213500976544, 2.1653213500976545, 2.5153213500976546, 2.8653213500976547, 3.2153213500976547, 3.565321350097655, 3.915321350097655, 4.265321350097655, 4.615321350097655, 4.965321350097654, 5.315321350097654, 5.665321350097654, 6.015321350097653, 6.365321350097653, 6.7153213500976525, 7.065321350097652, 7.415321350097652, 7.7653213500976515, 8.115321350097652, 8.465321350097652, 8.815321350097651, 9.165321350097651, 9.51532135009765, 9.86532135009765, 10.21532135009765, 10.56532135009765])

zmaginit = 13.
zmagfin = 23.
interval = 0.2
zmag_num = (zmagfin-zmaginit)/interval
zmag_edges, step = np.linspace(zmaginit, zmagfin, num=int(zmag_num), retstep=True)
print(type(zmag_edges))

print(len(rz_edges))
print(len(gr_edges))
print(len(zmag_edges))


<class 'numpy.ndarray'>
50
50
50


In [10]:
# create redshift bins

zinit = 0.2
zfin = 0.65
interval = 0.05
# num = (zfin-zinit)/interval
num = 10. 
zrange, step = np.linspace(zinit, zfin, num=int(num), retstep=True)

In [11]:
# models to test

gauss1 = np.random.normal(loc=1., scale=1., size=1)
print(int(gauss1))

gauss2 = np.random.normal(loc=2., scale=1., size=1)
print(int(gauss2))

gauss3 = np.random.normal(loc=3., scale=1., size=1)
print(int(gauss3))

gauss4 = np.random.normal(loc=4., scale=1., size=1)
print(int(gauss4))

gauss5 = np.random.normal(loc=5., scale=1., size=1)
print(int(gauss5))

gauss6 = np.random.normal(loc=6., scale=1., size=1)
print(int(gauss6))

gauss7 = np.random.normal(loc=7., scale=1., size=1)
print(int(gauss7))

gauss8 = np.random.normal(loc=8., scale=1., size=1)
print(int(gauss8))


0
2
2
5
5
6
7
9


In [12]:
# create a list of indices that matches ra_BKG

index_array = np.arange(len(raBKG))
print(len(index_array))
print(type(index_array))
# print(type(index_array[0]))

# randomly choose N number of indices (N being the number chosen by the number drawn from a gaussian distribution)

# import random

rand1 = np.random.choice(index_array, size=int(gauss1))
rand2 = np.random.choice(index_array, size=int(gauss2))
rand3 = np.random.choice(index_array, size=int(gauss3))
rand4 = np.random.choice(index_array, size=int(gauss4))
rand5 = np.random.choice(index_array, size=int(gauss5))
rand6 = np.random.choice(index_array, size=int(gauss6))
rand7 = np.random.choice(index_array, size=int(gauss7))
rand8 = np.random.choice(index_array, size=int(gauss8))

print(rand1)
print('----')
print(rand2)
print('----')
print(rand3)
print('----')
print(rand4)
print('----')
print(rand5)
print('----')
print(rand6)
print('----')
print(rand7)
print('----')
print(rand8)
print('----')


# find the colors and zmag for this source

gr_rand1 = grcolorBKG[rand1]
gr_rand2 = grcolorBKG[rand2]
gr_rand3 = grcolorBKG[rand3]
gr_rand4 = grcolorBKG[rand4]
gr_rand5 = grcolorBKG[rand5]
gr_rand6 = grcolorBKG[rand6]
gr_rand7 = grcolorBKG[rand7]
gr_rand8 = grcolorBKG[rand8]

rz_rand1 = rzcolorBKG[rand1]
rz_rand2 = rzcolorBKG[rand2]
rz_rand3 = rzcolorBKG[rand3]
rz_rand4 = rzcolorBKG[rand4]
rz_rand5 = rzcolorBKG[rand5]
rz_rand6 = rzcolorBKG[rand6]
rz_rand7 = rzcolorBKG[rand7]
rz_rand8 = rzcolorBKG[rand8]

zmag_rand1 = zmagBKG[rand1]
zmag_rand2 = zmagBKG[rand2]
zmag_rand3 = zmagBKG[rand3]
zmag_rand4 = zmagBKG[rand4]
zmag_rand5 = zmagBKG[rand5]
zmag_rand6 = zmagBKG[rand6]
zmag_rand7 = zmagBKG[rand7]
zmag_rand8 = zmagBKG[rand8]

# print(gr_rand1)
# print('----')
# print(gr_rand2)
# print('----')
# print(gr_rand3)
# print('----')
# print(gr_rand4)
# print('----')
# print(gr_rand5)
# print('----')
# print(gr_rand6)
# print('----')
# print(gr_rand7)
# print('----')
# print(gr_rand8)



517525
<class 'numpy.ndarray'>
[]
----
[381029 387323]
----
[372140   3290]
----
[299037 123305  95302 361703 365380]
----
[310638 302139 141842 324400  62925]
----
[137446 331647 369432 498885   1462  52656]
----
[212100 201570  35743 157021 392675  34392 375951]
----
[ 26683 335631  58137   2842 295810  18242 125430 449097  30545]
----


In [22]:
np.savez('/Users/mtownsend/Documents/LRG_Data/random_rzcolor.npz', rz_rand1=rz_rand1, rz_rand2=rz_rand2, rz_rand3=rz_rand3, rz_rand4=rz_rand4, rz_rand5=rz_rand5, rz_rand6=rz_rand6, rz_rand7=rz_rand7, rz_rand8=rz_rand8)
np.savez('/Users/mtownsend/Documents/LRG_Data/random_grcolor.npz', gr_rand1=gr_rand1, gr_rand2=gr_rand2, gr_rand3=gr_rand3, gr_rand4=gr_rand4, gr_rand5=gr_rand5, gr_rand6=gr_rand6, gr_rand7=gr_rand7, gr_rand8=gr_rand8)
np.savez('/Users/mtownsend/Documents/LRG_Data/random_zmag.npz', zmag_rand1=zmag_rand1, zmag_rand2=zmag_rand2, zmag_rand3=zmag_rand3, zmag_rand4=zmag_rand4, zmag_rand5=zmag_rand5, zmag_rand6=rz_rand6, zmag_rand7=rz_rand7, zmag_rand8=rz_rand8)

# data = np.load('/Users/mtownsend/Documents/LRG_Data/random_rzcolor.npz')
# data1 = data['rz_rand1']
# data2 = data['rz_rand2']

# print(len(data1))
# print(len(data2))


0
2


In [17]:
# using colors and zmag, place into null result
# median_zmag.py is similar to what I need for this, but needs to be modified to handle three dimensions

def loop_through_3D_array(arr, xedges, yedges, zedges, rz_rand, gr_rand, zmag_rand):
    # xedges = rz_edges
    # yedges = gr_edges
    # zedges = zmag_edges
    # arr = array to be changed
    # rz_rand, gr_rand, zmag_rand = rz color, gr color, zmag
    

    for i in range(len(rz_edges)-1):
        for j in range(len(gr_edges)-1):
            for k in range(len(zmag_edges)-1):
                for m in range(len(rz_rand)):
                    if ((rz_rand[m] >= rz_edges[i]) & (rz_rand[m] <= rz_edges[i + 1]) & (gr_rand[m] >= gr_edges[j]) & (gr_rand[m] <= gr_edges[j + 1]) & (zmag_rand[m] >= zmag_edges[k]) & (zmag_rand[m] <= zmag_edges[k + 1])):
                        arr[i][j][k] = arr[i][j][k] + 1
                        
    return arr




In [21]:
new_low_null_25_1 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand1, gr_rand1, zmag_rand1)
new_low_null_25_2 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand2, gr_rand2, zmag_rand2)
new_low_null_25_3 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand3, gr_rand3, zmag_rand3)
new_low_null_25_4 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand4, gr_rand4, zmag_rand4)
new_low_null_25_5 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand5, gr_rand5, zmag_rand5)
new_low_null_25_6 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand6, gr_rand6, zmag_rand6)
new_low_null_25_7 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand7, gr_rand7, zmag_rand7)
new_low_null_25_8 = loop_through_3D_array(low_null_25, rz_edges, gr_edges, zmag_edges, rz_rand8, gr_rand8, zmag_rand8)

print(new_low_null_25_1.shape)
print(new_low_null_25_2.shape)
print(new_low_null_25_3.shape)
print(new_low_null_25_4.shape)
print(new_low_null_25_5.shape)
print(new_low_null_25_6.shape)
print(new_low_null_25_7.shape)
print(new_low_null_25_8.shape)
print(low_null_25.shape)

np.savez('/Users/mtownsend/Documents/LRG_Data/new_null_low_25.npz', new_low_null_25_1=new_low_null_25_1, new_low_null_25_2=new_low_null_25_2, new_low_null_25_3=new_low_null_25_3, new_low_null_25_4=new_low_null_25_4, new_low_null_25_5=new_low_null_25_5, new_low_null_25_6=new_low_null_25_6, new_low_null_25_7=new_low_null_25_7, new_low_null_25_8=new_low_null_25_8)

data = np.load('/Users/mtownsend/Documents/LRG_Data/new_null_low_25.npz')
data1 = data['new_low_null_25_1']
data2 = data['new_low_null_25_2']
data3 = data['new_low_null_25_3']
data4 = data['new_low_null_25_4']
data5 = data['new_low_null_25_5']
data6 = data['new_low_null_25_6']
data7 = data['new_low_null_25_7']
data8 = data['new_low_null_25_8']
print(data1.shape)
print(data2.shape)
print(data3.shape)
print(data4.shape)
print(data5.shape)
print(data6.shape)
print(data7.shape)
print(data8.shape)




(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)
(2522, 49, 49, 49)


In [37]:
# using colors and zmag, place into null result

arr, edges = np.histogramdd((rzcolorBKG[0:10], grcolorBKG[0:10], zmagBKG[0:10]), bins=(2,2,2), density=False)

rz_edges = edges[0]
gr_edges = edges[1]
zmag_edges = edges[2]

print(rz_edges)
print(gr_edges)
print(zmag_edges)

print('----')

print(rz_rand3)
print(gr_rand3)
print(zmag_rand3)

rz_rand = rz_rand3
gr_rand = gr_rand3
zmag_rand = zmag_rand3

print('----')

print(arr)

print('----')

for i in range(len(rz_edges)-1):
    for j in range(len(gr_edges)-1):
        for k in range(len(zmag_edges)-1):
            for m in range(len(rand)):
                if ((rz_rand[m] >= rz_edges[i]) & (rz_rand[m] <= rz_edges[i + 1]) & (gr_rand[m] >= gr_edges[j]) & (gr_rand[m] <= gr_edges[j + 1]) & (zmag_rand[m] >= zmag_edges[k]) & (zmag_rand[m] <= zmag_edges[k + 1])):
                    arr[i][j][k] = arr[i][j][k] + 1
                    
print(arr)


[0.24726677 1.33673859 2.4262104 ]
[0.59529686 2.32224369 4.04919052]
[20.43336296 21.39186001 22.35035706]
----
[1.457962  0.7939091 1.7423344]
[2.0618458  0.85702896 0.38645363]
[22.28767  21.946096 22.280119]
----
[[[6. 2.]
  [0. 0.]]

 [[0. 1.]
  [1. 0.]]]
----
[[[6. 3.]
  [0. 0.]]

 [[0. 2.]
  [1. 0.]]]
